parameters:
    migrator_jekyll:
        paths_to_remove:
            - 'Gemfile'
            - 'Gemfile.lock'
            - 'Guardfile'
            - '_templates'

        paths_to_move:
            # renames
            '_includes': 'source/_snippets'

            # fnmatch match
            '*.md': 'source/'

            # same
            'favicon.ico': 'source/favicon.ico'
            'favicon.png': 'source/favicon.png'
            '_config.yml': 'source/_config.yml'
            'feed.xml': 'source/feed.xml'
            'Gruntfile.js': 'source/Gruntfile.js'
            'assets': 'source/assets'
            'images': 'source/images'
            '_posts': 'source/_posts'
            '_layouts': 'source/_layouts'
            '_drafts': 'source/_drafts'
            '_data': 'source/_data'
            '_sass': 'source/_sass'
            'CNAME': 'source/CNAME'

        apply_regular_in_paths:
            'source/_posts':
                 # remove layout from posts, not needed
                '#^layout: \w+\s+#ms': ''
            'source':
                # parameters are accessed directly, without any prefix - see https://regex101.com/r/PvaeHS/1
                '#{{\s+?\b(site\.data\.|site\.)[\w+]#': '$1$3'
                # remove --- --- in the start
                '#^\-\-\-\n\-\-\-\n#m': ''

services:
    _defaults:
        autowire: true

    Symplify\Statie\MigratorJekyll\:
        resource: '../src'
        exclude: '../src/{Contract}'
