parameters:
    directories_to_repositories: []
    subsplit_cache_directory: '%kernel.cache_dir%/_subsplit'

    # create token here: https://github.com/settings/tokens/new
    # use in cli like: "GITHUB_TOKEN=%s vendor/bin/monorepo-builder split ..."
    env(GITHUB_TOKEN): null
    github_token: '%env(GITHUB_TOKEN)%'

imports:
    - { resource: 'services.yml' }
