services:
    _defaults:
        public: true
        autowire: true

    Symplify\MonorepoBuilder\Split\:
        resource: '..'
        exclude: '../{Exception,Process/SplitProcessInfo.php}'

    Symplify\PackageBuilder\FileSystem\FileSystemGuard: ~
