services:
    _defaults:
        autowire: true
        bind:
            $directoriesToRepositories: '%directories_to_repositories%'
            $rootDirectory: '%root_directory%'
            $repository: '%root_directory%/.git'
            $subsplitCacheDirectory: '%subsplit_cache_directory%'
            $githubToken: '%github_token%'
            $githubUserName: '%github_user_name%'

    Symplify\MonorepoBuilder\Split\:
        resource: '..'
        exclude: '../{Exception,Process/SplitProcessInfo.php}'

    Symplify\PackageBuilder\FileSystem\FileSystemGuard: ~
