services:
    _defaults:
        autowire: true
        bind:
            $directoriesToRepositories: '%directories_to_repositories%'
            $rootDirectory: '%root_directory%'
            $subsplitCacheDirectory: '%subsplit_cache_directory%'

    Symplify\MonorepoBuilder\Split\:
        resource: '..'
        exclude: '../{Exception,Process/SplitProcessInfo.php}'

    Symplify\PackageBuilder\FileSystem\FileSystemGuard: ~
