imports:
    - { resource: '../../packages/**/src/config/services.yml' }
    - { resource: 'services.yml' }
    - { resource: 'external-services.yml' }

parameters:
    # defaults for "PhpCsFixer\WhitespacesFixerConfig"
    indentation: 'spaces'
    line_ending: !php/const PHP_EOL

    cache_directory: '%sys_get_temp_dir%/_changed_files_detector%env(TEST_SUFFIX)%'
    skip: []
    exclude_files: []
    root_skip: []
    # for tests
    env(TEST_SUFFIX): ''

    collectors:
        -
            main_type: 'Symplify\EasyCodingStandard\SniffRunner\Application\SniffFileProcessor'
            collected_type: 'PHP_CodeSniffer\Sniffs\Sniff'
            add_method: 'addSniff'
        -
            main_type: 'Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor'
            collected_type: 'PhpCsFixer\Fixer\FixerInterface'
            add_method: 'addFixer'
