services:
    _defaults:
        autowire: true

    # Console
    Symfony\Component\Console\Terminal: ~
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    # for autowired checkers
    Symplify\TokenRunner\DocBlock\DescriptionAnalyzer:
    Symplify\TokenRunner\DocBlock\ParamAndReturnTagAnalyzer: ~
    Symplify\TokenRunner\Analyzer\FixerAnalyzer\DocBlockFinder: ~
    Symplify\TokenRunner\Analyzer\FixerAnalyzer\TokenSkipper: ~

    # conditional PSR-4 from vendor? or import?
    Symplify\TokenRunner\Wrapper\FixerWrapper\DocBlockWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\ClassWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\PropertyWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\PropertyAccessWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\MethodWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\ArrayWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\ArgumentWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\FixerWrapper\MethodCallWrapperFactory: ~
    Symplify\TokenRunner\Wrapper\SnifferWrapper\ClassWrapperFactory: ~
    Symplify\TokenRunner\Transformer\FixerTransformer\UseImportsTransformer: ~

    Symplify\TokenRunner\Analyzer\SnifferAnalyzer\Naming: ~
    Symplify\TokenRunner\Naming\Name\NameFactory: ~
    Symplify\TokenRunner\Analyzer\FixerAnalyzer\ClassNameFinder: ~
    Symplify\TokenRunner\Naming\Name\NameAnalyzer: ~
    Symplify\CodingStandard\Fixer\TokenBuilder: ~

    Symplify\BetterReflectionDocBlock\DocBlockSerializerFactory: ~
    Symplify\BetterReflectionDocBlock\CleanDocBlockFactory: ~
    Symplify\TokenRunner\Analyzer\FixerAnalyzer\IndentDetector: ~

    Symplify\TokenRunner\Guard\TokenTypeGuard: ~

    PhpCsFixer\Tokenizer\Analyzer\NamespaceUsesAnalyzer: ~
    PhpCsFixer\Tokenizer\Analyzer\NamespacesAnalyzer: ~
    phpDocumentor\Reflection\FqsenResolver: ~
