imports:
    - { resource: '../../packages/**/src/config/services.yml' }
    - { resource: 'external-services.yml' }

services:
    _defaults:
        autowire: true
        public: true # for tests

    Symplify\EasyCodingStandard\:
        resource: '../../src'
        exclude: '../../src/{Contract,Configuration/Loader/NeonLoader.php,DependencyInjection,Exception,Error/Error.php,Error/FileDiff.php}'

    _instanceof:
        Symplify\EasyCodingStandard\Contract\Application\FileProcessorCollectorInterface:
            calls:
                # orders matters, so Fixer can cleanup after Sniffer
                - ['addFileProcessor', ['@Symplify\EasyCodingStandard\SniffRunner\Application\SniffFileProcessor']]
                - ['addFileProcessor', ['@Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor']]
