services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Symplify\EasyCodingStandard\:
        resource: '../../src'
        exclude: '../../src/{Contract,Exception,Error/Error.php,Application/Command,DependencyInjection,Configuration/Loader/NeonLoader.php}'
    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '../../packages/ChangedFilesDetector/src'
        exclude: '../../packages/ChangedFilesDetector/src/{Cache/CacheFactory}'
    Symplify\EasyCodingStandard\Configuration\:
        resource: '../../packages/Configuration/src'
        exclude: '../../packages/Configuration/src/{Exception}'
    Symplify\EasyCodingStandard\SniffRunner\:
        resource: '../../packages/SniffRunner/src'
        exclude: '../../packages/SniffRunner/src/{Exception,File/File.php,Event}'
    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '../../packages/FixerRunner/src'
        exclude: '../../packages/FixerRunner/src/{Exception}'

    # 3rd party services
    Nette\DI\Config\Loader: ~
    SebastianBergmann\Diff\Differ: ~
    Symfony\Component\Console\Terminal: ~

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Output\ConsoleOutput: ~

    Symfony\Component\Console\Style\SymfonyStyle: ~

    # alias required for SymfonyStyle
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput
