imports:
    - { resource: '../../packages/**/src/config/services.yml' }
    - { resource: 'external-services.yml' }

services:
    _defaults:
        autowire: true
        public: true # for tests

    Symplify\EasyCodingStandard\:
        resource: '../../src'
        exclude: '../../src/{Application/Application.php,Contract,Configuration/Loader/NeonLoader.php,DependencyInjection,Exception,Error/Error.php,Error/FileDiff.php}'

    Symplify\EasyCodingStandard\Application\Application:
        calls:
            # exact in that order, so Fixer can cleanup after Sniffer
            - ['addFileProcessor', ['@Symplify\EasyCodingStandard\SniffRunner\Application\SniffFileProcessor']]
            - ['addFileProcessor', ['@Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor']]
