services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Symplify\EasyCodingStandard\:
        resource: '../../src'
        exclude: '../../src/{Contract,Exception,Error/Error.php,Application/Command,DependencyInjection,Configuration/Loader/NeonLoader.php}'
    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '../../packages/ChangedFilesDetector/src'
        exclude: '../../packages/ChangedFilesDetector/src/{Cache/CacheFactory}'
    Symplify\EasyCodingStandard\Configuration\:
        resource: '../../packages/Configuration/src'
        exclude: '../../packages/Configuration/src/{Exception}'
    Symplify\EasyCodingStandard\SniffRunner\:
        resource: '../../packages/SniffRunner/src'
        exclude: '../../packages/SniffRunner/src/{Exception,File/File.php,TokenDispatcher/Event}'
    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '../../packages/FixerRunner/src'
        exclude: '../../packages/FixerRunner/src/{Exception}'

    Symfony\Component\Console\Application: ~
    Symfony\Component\Console\Terminal: ~
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Output\ConsoleOutput: ~
