services:
    Symplify\ChangelogLinker\Worker\BracketsAroundReferencesWorker:
    Symplify\ChangelogLinker\Worker\DiffLinksToVersionsWorker:
    Symplify\ChangelogLinker\Worker\LinkifyWorker:
    Symplify\ChangelogLinker\Worker\ShortenReferencesWorker:
    Symplify\ChangelogLinker\Worker\UserReferencesWorker:
    Symplify\ChangelogLinker\Worker\LinksToReferencesWorker:
