services:
    _defaults:
        bind:
            $repositoryUrl: "%repository_url%"
            $namesToUrls: "%names_to_urls%"

    Symplify\ChangelogLinker\Worker\BracketsAroundReferencesWorker:
    Symplify\ChangelogLinker\Worker\DiffLinksToVersionsWorker:
    Symplify\ChangelogLinker\Worker\LinkifyWorker:
    Symplify\ChangelogLinker\Worker\UserReferencesWorker:
    Symplify\ChangelogLinker\Worker\LinksToReferencesWorker:
