# see https://kodiakhq.com/docs/quickstart?installation_id=8093536&setup_action=install
# Minimal config. version is the only required field.
version = 1

merge.delete_branch_on_merge = true
merge.method = "squash"

# see https://kodiakhq.com/docs/config-reference#approveauto_approve_usernames
approve.auto_approve_usernames = ["TomasVotruba"]
