language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml" STATIC_ANALYSIS=true
    - php: 7.2

install:
  - composer install

before_script:
  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - |
    if [[ $STATIC_ANALYSIS != "" ]]; then
      composer check-cs
      composer phpstan
    fi

after_script:
  # upload coverage.xml to Coveralls
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php coveralls.phar --verbose
    fi

notifications:
  email: never
