language: php

php: 7.4

branches:
    only:
        - master

script:
    # disable xdebug to speed up
    - phpenv config-rm xdebug.ini
    - composer update
    - packages/monorepo-builder/bin/monorepo-builder split --max-processes 6

notifications:
    email: false
