language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: 7.1
      env: CODING_STANDARD=true
    - php: 7.2
      env: PHPSTAN=true MONOREPO_SPLIT=true
    - php: 7.2
      env: STANDALONE=true

install:
  - composer install

before_script:
  # to make multiline scripts report fails
  - set -e
  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0

  # static analysis
  - if [[ $CODING_STANDARD != "" ]]; then packages/EasyCodingStandard/bin/ecs check packages; fi
  - if [[ $PHPSTAN != "" ]]; then vendor/bin/phpstan analyse packages --level max --configuration phpstan.neon; fi
  - |
    if [[ $STANDALONE != "" ]]; then
      vendor/bin/phpunit packages/BetterReflectionDocBlock;
      vendor/bin/phpunit packages/ChangelogLinker;
      vendor/bin/phpunit packages/CodingStandard;
      vendor/bin/phpunit packages/EasyCodingStandard
      vendor/bin/phpunit packages/PackageBuilder;
      vendor/bin/phpunit packages/Statie;
      vendor/bin/phpunit packages/TokenRunner;
    fi

after_script:
  # upload coverage.xml to Coveralls
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
      php coveralls.phar --verbose;
    fi
  # split monorepo to packages (done via Travis Cron Job)
  - if [[ $TRAVIS_EVENT_TYPE = "cron" && $MONOREPO_SPLIT != "" ]]; then bin/subtree-split-master-and-last-tag.sh; fi

notifications:
  email: never
