os: linux

language: php

script:
    - vendor/bin/phpunit

install:
    - composer update

before_install:
    # disable xdebug if not coverage
    - phpenv config-rm xdebug.ini

jobs:
    include:
        -
            stage: deploy
            name: 'Split Monorepo'
            if: branch = master AND type = push
            php: 7.3
            script:
                # split monorepo to packages - only on merge to master
                # see https://www.tomasvotruba.cz/blog/2018/07/19/how-to-make-github-and-travis-split-monorepo-to-multiple-git-repositories-for-you/
                - packages/MonorepoBuilder/bin/monorepo-builder split --max-processes 7

notifications:
    email: false
