language: php

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml" CHECK_CS=1 RUN_PHPSTAN=1

install:
  # to fasten up installation with parallel downloading
  - composer global require "hirak/prestissimo:^0.3"
  # install composer dependencies
  - composer install

script:
  # run tests
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # check coding standard (defined in composer.json "scripts" section)
  - if [[ $CHECK_CS = 1 ]]; then composer check-cs; fi
  # check with phpstan
  - if [[ $RUN_PHPSTAN = 1 ]]; then composer phpstan; fi

after_script:
  # upload coverage.xml file to Scrutinizer to analyze it
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
