language: php

matrix:
  include:
    # run extra build with PHP 7.1
    - php: 7.1
      # add variables to enable coverage, coding standard check and static analysis
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"

install:
  # install composer dependencies
  - composer install

script:
  # run tests
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # check coding standard (defined in composer.json "scripts" section)
  - composer check-cs
  # check with phpstan (defined in composer.json "scripts" section)
  - composer phpstan

after_script:
  # upload coverage.xml file to Scrutinizer to analyze it
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
