# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

dist: bionic

php: 7.4

jobs:
    include:
        -
            name: "Split Monorepo"
            if: (branch = master OR tag IS present) && type = push
            script:
                - composer update --ansi
                # travis_retry to prevent fails
                - travis_retry packages/monorepo-builder/bin/monorepo-builder split --max-processes 6 --ansi

notifications:
    email: false
