language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
  depth: false

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: 7.1
      env: CODING_STANDARD=true
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: PHPSTAN=true MONOREPO_SPLIT=true
    - php: 7.2
      env: STANDALONE=true

install:
  - composer update $COMPOSER_FLAGS

before_script:
  # make the script fail for any failed command
  - set -e

  # disable xdebug if not coverage
  - if [[ $PHPUNIT_FLAGS = "" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0

  # static analysis
  - if [[ $CODING_STANDARD == true ]]; then packages/EasyCodingStandard/bin/ecs check packages; fi
  - if [[ $PHPSTAN == true ]]; then vendor/bin/phpstan analyse packages --level max --configuration phpstan.neon; fi

  # each package standalone run https://stackoverflow.com/a/6787956/1348344
  - |
    if [[ $STANDALONE == true ]]; then
      for DIRECTORY in `find packages -mindepth 1 -maxdepth 1 -type d`;
      do
        vendor/bin/phpunit $DIRECTORY
      done
    fi

  # validate monorepo <=> packages composer dependencies
  - packages/MonorepoBuilder/bin/monorepo-builder validate-versions

after_script:
  # upload coverage.xml to Coveralls
  - |
    if [[ $PHPUNIT_FLAGS == true ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
      php coveralls.phar --verbose;
    fi

  # split monorepo to packages - only on merge to master
  - |
    if [[ $TRAVIS_EVENT_TYPE == "push" && $MONOREPO_SPLIT == true && $TRAVIS_BRANCH == "master" ]]; then
      packages/MonorepoBuilder/bin/monorepo-builder split -v
    fi

  # debug
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_BRANCH
  - git tag

notifications:
  email: never
