services:
    _defaults:
        public: true
        autowire: true

    Symplify\LatteToTwigConverter\:
        resource: ".."
        exclude: "../{Contract}"

    Symfony\Component\Console\Application: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
