jobs:
    # see https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32163/highlight/true#M1024
    get_tag:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -
                id: get_tag
                # see https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32163/highlight/true#M1024
                run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    ecs_phar_compile:
            -
                name: Publish ecs.phar to symplify/easy-coding-standard-prefixed
                run: |
                    # push tag, if this commit is tagged, or with normal push
                    if [ "${CURRENT_TAG}" != "" ]; then git tag "${CURRENT_TAG}" && git push --quiet origin ${CURRENT_TAG}; fi
                env:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    CURRENT_TAG: ${{ steps.get_tag.outputs.VERSION }}
