services:
    _defaults:
        public: true
        autowire: true

    Symplify\NeonToYamlConverter\:
        resource: "../src"
        exclude: "../src/{HttpKernel/NeonToYamlConverterKernel.php}"

    Symfony\Component\Console\Application: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
    Symfony\Component\Filesystem\Filesystem: ~
    Symplify\PackageBuilder\Strings\StringFormatConverter: ~
