services:
    _defaults:
        public: true
        autowire: true

    Symplify\NeonToYamlConverter\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/NeonToYamlConverterKernel.php'

    Symfony\Component\Filesystem\Filesystem: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\SmartFileSystem\Finder\FinderSanitizer: ~
    Symplify\PackageBuilder\Strings\StringFormatConverter: ~
