parameters:
    authors_to_ignore: []
    names_to_urls: []
    package_aliases: []
    # e.g.: CS: 'CodingStandard'

    # create token here: https://github.com/settings/tokens/new
    # use in cli like: "GITHUB_TOKEN=%s vendor/bin/changelog-linker dump-merges ..."
    env(GITHUB_TOKEN): null
    github_token: '%env(GITHUB_TOKEN)%'

services:
    _defaults:
        autowire: true
        public: true

    Symplify\SmartFileSystem\FileSystemGuard: null

    Symplify\ChangelogLinker\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel'
            - '../src/DependencyInjection/CompilerPass'
            - '../src/Exception'
            - '../src/ChangeTree/Change.php'

    Symplify\PackageBuilder\Yaml\ParametersMerger: null
    Symplify\PackageBuilder\Parameter\ParameterProvider: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    GuzzleHttp\Client: null
