services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '..'
        exclude: '../{Exception}'

    Symfony\Component\Stopwatch\Stopwatch: ~

    # differ
    PhpCsFixer\Differ\SebastianBergmannShortDiffer: ~
    PhpCsFixer\Differ\DifferInterface:
        alias: PhpCsFixer\Differ\SebastianBergmannShortDiffer

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:
        public: true # for tests
