services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '..'
        exclude: '../{Exception}'

    Symfony\Component\Stopwatch\Stopwatch: ~

    # differ
    SebastianBergmann\Diff\Differ: ~

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:
        public: true # for tests
