services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '..'
        exclude: '../{Exception}'

    Symfony\Component\Stopwatch\Stopwatch: ~

    # differ
    Symplify\EasyCodingStandard\FixerRunner\Differ\LineLimitSebastianBergmannDiffer: ~
    PhpCsFixer\Differ\DifferInterface:
        alias: Symplify\EasyCodingStandard\FixerRunner\Differ\LineLimitSebastianBergmannDiffer

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:
        public: true # for tests
