services:
    Symplify\EasyCodingStandard\FixerRunner\:
        resource: '..'
        exclude: '../{Exception}'

    # differ
    PhpCsFixer\Differ\UnifiedDiffer: ~

    Symplify\EasyCodingStandard\FixerRunner\Application\FixerFileProcessor:

    PhpCsFixer\WhitespacesFixerConfig:
        factory: ['@Symplify\EasyCodingStandard\FixerRunner\WhitespacesFixerConfigFactory', 'create']
