parameters:
    twig_cache_directory: '%kernel.cache_dir%/twig'

services:
    _defaults:
        autowire: true
        bind:
            $twigCacheDirectory: '%twig_cache_directory%'

    Symplify\Statie\Twig\:
        resource: '..'

    # twig setup
    Twig\Loader\ArrayLoader:

    Twig\Environment:
        factory: ['@Symplify\Statie\Twig\TwigFactory', 'create']

    Latte\Runtime\FilterExecutor: