services:
    _defaults:
        autowire: true
        bind:
            $cacheDirectory: '%cache_directory%'

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'

    Symfony\Component\Cache\Simple\FilesystemCache: ~
    Symfony\Component\Cache\Adapter\SimpleCacheAdapter: ~
