services:
    _defaults:
        autowire: true
        public: true # for tests
        bind:
            $cacheDirectory: '%cache_directory%'

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'
        exclude: '../{Cache/CacheFactory}'
