services:
    _defaults:
        autowire: truega
        public: true # for tests

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'
        exclude: '../{Cache/CacheFactory}'
