services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'
        exclude: '../{Cache/CacheFactory}'

    Symplify\EasyCodingStandard\ChangedFilesDetector\ChangedFilesDetector:
        public: true
