services:
    _defaults:
        autowire: true
        bind:
            $cacheDirectory: '%cache_directory%'

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'
#        exclude: '../{Cache/CacheFactory}'

    Nette\Caching\Cache:
        factory: ['@Symplify\EasyCodingStandard\ChangedFilesDetector\Cache\CacheFactory', 'create']
