services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\ChangedFilesDetector\:
        resource: '..'

    Symfony\Component\Cache\Simple\FilesystemCache:
        $directory: '%cache_directory%'

    Symfony\Component\Cache\Adapter\SimpleCacheAdapter: ~
