services:
    _defaults:
        autowire: true
        public: true # for statie.bin file

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    # Symfony Console
    Symfony\Component\Console\Input\ArgvInput: ~

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symfony\Component\EventDispatcher\EventDispatcher: ~

    GitWrapper\GitWrapper: ~