imports:
    # optional import of GitWrapper services
    - { resource: '../../../GitWrapper/src/config/services.yml' }
    - { resource: '../../../GitWrapper/src/config/external-services.yml' }

services:
    _defaults:
        autowire: true
        public: true # for statie.bin file

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

#    Symplify\GitWrapper\GitWrapper: ~

    # Symfony Console
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: Symfony\Component\EventDispatcher\EventDispatcher
