services:
    _defaults:
        autowire: true

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    Symfony\Component\Console\Input\ArgvInput:
        public: true

    Symfony\Component\Console\Output\ConsoleOutput:
        public: true

    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symfony\Component\EventDispatcher\EventDispatcher: ~

    Symfony\Component\Yaml\Parser: ~
