services:
    _defaults:
        public: true
        autowire: true

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~

    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\Yaml\Parser: ~
    Symfony\Component\Filesystem\Filesystem: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
