imports:
    - { resource: '../../packages/**/src/config/services.yml' }

services:
    _defaults:
        autowire: true
        public: true # for tests

    # PSR-4 autodiscovery
    Symplify\Statie\:
        resource: ../../src
        exclude: ../../src/{Exception,Renderable/File/File.php,Renderable/File/PostFile.php}

    # 3rd party services
    Symfony\Component\Console\Application: ~

    ParsedownExtra:
        class: ParsedownExtra

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    GitWrapper\GitWrapper: ~
