imports:
    - { resource: '../../packages/**/src/config/services.yml' }

services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    Symplify\Statie\:
        resource: ../../src
        exclude: ../../src/{Exception,Renderable/File/File.php,Renderable/File/PostFile.php}

    # 3rd party services
    Symfony\Component\Console\Application: ~
    parsedown_extra:
        class: ParsedownExtra
    Lullabot\AMP\AMP: ~
    Symplify\PackageBuilder\Adapter\Symfony\Parameter\ParameterProvider: ~

    GitWrapper\GitWrapper: ~
