services:
    _defaults:
        autowire: true

    Symplify\Statie\:
        resource: '../../src'
        exclude: '../../src/{Exception,Renderable/File/File.php,Renderable/File/PostFile.php,Event}'

    # bin file
    Symplify\Statie\Console\Application:
        public: true
