services:
    _defaults:
        autowire: true

    Symplify\Statie\FlatWhite\:
        resource: ../
        public: true # for tests

    Latte\ILoader:
        alias: Symplify\Statie\FlatWhite\Latte\DynamicStringLoader
