imports:
    - { resource: "services.yml" }

parameters:
    authors_to_ignore: []
    names_to_urls: []
    package_aliases: []
    # e.g.: CS: 'CodingStandard'

    # create token here: https://github.com/settings/tokens/new
    # use in cli like: "GITHUB_TOKEN=%s vendor/bin/changelog-linker dump-merges ..."
    env(GITHUB_TOKEN): null
    github_token: '%env(GITHUB_TOKEN)%'
