imports:
    - { resource: "services.yml" }

parameters:
    authors_to_ignore: []
#    repository_url: "https://github.com/dummy/dummy"
    linkify: []

    package_aliases: []
    # e.g. [CS] => [CodingStandard]
