services:
    _defaults:
        autowire: true
        bind:
            $repositoryLink: "%repository_link%"

    Symplify\ChangelogLinker\:
        resource: '..'
        exclude: '../{Contract}'

    Symfony\Component\Console\Application:
        public: true # for bin file