services:
    _defaults:
        autowire: true
        bind:
            $author: "%author%"
            $repositoryUrl: "%repository_url%"
            $repositoryName: "%repository_name%"
            $nameToUrls: "%linkify%"

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception}"

    Symplify\ChangelogLinker\Console\Application:
        public: true # for bin file