services:
    _defaults:
        autowire: true
        bind:
            $authorsToIgnore: "%authors_to_ignore%"
            $repositoryUrl: "%repository_url%"
            $repositoryName: "%repository_name%"
            $namesToUrls: "%names_to_urls%"
            $packageAliases: "%package_aliases%"

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Console\ConfigAwareApplication:
        public: true # for bin file

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~

    GuzzleHttp\Client: ~

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~
