services:
    _defaults:
        autowire: true
        bind:
            $repositoryLink: "%repository_link%"

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception}"

    Symplify\ChangelogLinker\Console\Application:
        public: true # for bin file