services:
    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Console\ConfigAwareApplication: ~

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~

    GuzzleHttp\Client: ~

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~
