services:
    _defaults:
        public: true
        autowire: true

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,DependencyInjection/CompilerPass,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    GuzzleHttp\Client: ~

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~
