services:
    _defaults:
        autowire: true
        bind:
            $repositoryUrl: "%repository_url%"

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception}"

    Symplify\ChangelogLinker\Console\Application:
        public: true # for bin file