services:
    _defaults:
        public: true
        autowire: true

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,DependencyInjection/CompilerPass,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    GuzzleHttp\Client: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
