services:
    _defaults:
        autowire: true
        bind:
            $authorsToIgnore: "%authors_to_ignore%"
            $repositoryUrl: "%repository_url%"
            $repositoryName: "%repository_name%"
            $nameToUrls: "%linkify%"

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,Exception,Worker,ChangeTree/Change.php}"

    Symplify\ChangelogLinker\Console\Application:
        public: true # for bin file

    GuzzleHttp\Client: ~

    # SymfonyStyle
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: 'Symfony\Component\Console\Input\ArgvInput'
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: 'Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Style\SymfonyStyle: ~
