services:
    _defaults:
        public: true
        autowire: true

    Symplify\ChangelogLinker\:
        resource: ".."
        exclude: "../{Contract,DependencyInjection/CompilerPass,Exception,ChangeTree/Change.php}"

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~

    GuzzleHttp\Client: ~
