services:
    _defaults:
        autowire: true
        public: true # for tests

    Symplify\BetterReflectionDocBlock\:
        resource: '../'
        exclude: '../{CleanFormatter.php,DependencyInjection,Tag/*}'
<<<<<<< HEAD
=======

    phpDocumentor\Reflection\FqsenResolver: ~

    PHPStan\PhpDocParser\Lexer\Lexer: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~
    PHPStan\PhpDocParser\Parser\PhpDocParser: ~
>>>>>>> [BetterReflectionDocBlock] add DI container
