services:
    _defaults:
        autowire: true

    Symplify\BetterReflectionDocBlock\:
        resource: '../'
        exclude: '../{DependencyInjection,PhpDocParser/PhpDocInfo.php,Tag/*,PhpDocParser/Ast/Type/*}'

    PHPStan\PhpDocParser\Lexer\Lexer: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~

    PHPStan\PhpDocParser\Parser\PhpDocParser:
        alias: 'Symplify\BetterReflectionDocBlock\PhpDocParser\PositionAwarePhpDocParser'
