services:
    _defaults:
        autowire: true
        public: true # for tests

    Symplify\BetterReflectionDocBlock\:
        resource: '../'
        exclude: '../{CleanFormatter.php,DependencyInjection,Tag/*}'
