services:
    _defaults:
        public: true
        autowire: true

    Symplify\LatteToTwigConverter\:
        resource: '../src'
        exclude:
            - '../src/Contract'
            - '../src/Exception'
            - '../src/HttpKernel/LatteToTwigConverterKernel.php'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\SmartFileSystem\Finder\FinderSanitizer: ~
    Symfony\Component\Filesystem\Filesystem: ~
