services:
    _defaults:
        public: true
        autowire: true

    Symplify\LatteToTwigConverter\:
        resource: "../src"
        exclude: "../src/{Contract,Exception}"

    Symfony\Component\Console\Application: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
    Symfony\Component\Filesystem\Filesystem: ~
