services:
    _defaults:
        public: true
        autowire: true

    Symplify\LatteToTwigConverter\:
        resource: "../src"
        exclude: "../src/{Contract,Exception,HttpKernel/LatteToTwigConverterKernel.php}"

    Symfony\Component\Console\Application:
        alias: 'Symplify\LatteToTwigConverter\Console\LatteToTwigConverterApplication'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
    Symfony\Component\Filesystem\Filesystem: ~
