services:
    _defaults:
        autowire: true
        public: true

    Symplify\Autodiscovery\:
        resource: '../src'
        exclude:
            - '../src/Contract/'
            - '../src/HttpKernel/AutodiscoveryKernel.php'
            - '../src/FileSystem.php'
            - '../src/*/*Autodiscoverer.php'
            - '../src/Discovery.php'

    Symfony\Component\Filesystem\Filesystem: ~
    Symplify\SmartFileSystem\Finder\FinderSanitizer: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
