services:
    _defaults:
        autowire: true
        public: true

    Symplify\Autodiscovery\:
        resource: '../src'
        exclude: '../src/{Contract,DependencyInjection,AutodiscovererCollector.php,Doctrine/DoctrineEntityMappingAutodiscoverer.php,FileSystem.php,Routing/AnnotationRoutesAutodiscover.php,Twig/TwigPathAutodiscoverer.php}'

    Symfony\Component\Console\Application: ~
    Symfony\Component\Filesystem\Filesystem: ~
