services:
    _defaults:
        autowire: true
        public: true

    Symplify\Autodiscovery\:
        resource: '../src'
        exclude: '../src/{Contract,DependencyInjection,AutodiscovererCollector.php,FileSystem.php,*/*Autodiscoverer.php}'

    Symfony\Component\Console\Application: ~
    Symfony\Component\Filesystem\Filesystem: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
