imports:
    - { resource: 'clean-code.yml' }
    - { resource: 'common.yml' }
    - { resource: 'php70.yml' }
    - { resource: 'php71.yml' }
    - { resource: 'psr2.yml' }
    - { resource: 'psr12.yml' }
    - { resource: 'symfony.yml' }
    - { resource: 'symfony-risky.yml' }
    - { resource: 'symplify.yml' }

parameters:
    exclude_checkers:
        - 'PhpCsFixer\Fixer\Operator\NotOperatorWithSuccessorSpaceFixer'