imports:
    - { resource: '../packages/**/config/services.yml' }
    - { resource: 'services.yml' }
    # A. in monorepo
    - { resource: '../../TokenRunner/config/config.yml', ignore_errors: true }
    # B. as dependency
    - { resource: '%vendor%/symplify/token-runner/config/config.yml', ignore_errors: true }

parameters:
    # defaults for "PhpCsFixer\WhitespacesFixerConfig"
    indentation: 'spaces'
    line_ending: !php/const PHP_EOL

    cache_directory: '%sys_get_temp_dir%/_changed_files_detector%env(TEST_SUFFIX)%'
    skip: []
    exclude_files: []
    # for tests
    env(TEST_SUFFIX): ''
