language: php

php:
  - 7.1

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS="--coverage-clover coverage.clover" CHECK_CS=true

install:
  - composer install --prefer-source

before_script:
  # check coding standard
  - if [[ $CHECK_CS != "" ]]; then composer check-cs; fi

script:
  # run tests
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  # get scrutinizer and upload coverage
  - if [[ $PHPUNIT_FLAGS != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

# do not send success notifications, they have no value
notifications:
  email:
    on_success: never
