parameters:
    post_headline_linker_enabled: false
    post_headline_linker_min_level: 1
    post_headline_linker_max_level: 6

services:
    _defaults:
        autowire: true

    Symplify\Statie\PostHeadlineLinker\:
        resource: '../src'
