services:
    _defaults:
        public: true
        autowire: true

    Symplify\MonorepoBuilder\:
        resource: '..'
        exclude: '../{Contract,Exception}'

    Symplify\PackageBuilder\Yaml\ParametersMerger: ~

    Symplify\MonorepoBuilder\Console\MonorepoBuilderApplication:
        calls:
        - ['setDispatcher', ['@Symfony\Component\EventDispatcher\EventDispatcher']]
    Symfony\Component\Console\Application:
        alias: 'Symplify\MonorepoBuilder\Console\MonorepoBuilderApplication'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    # alias needed for Symfony Console setter
    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: 'Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\Filesystem\Filesystem: ~
