services:
    _defaults:
        autowire: true

    Symplify\Statie\Generator\:
        resource: ../
        exclude: ../{Configuration/GeneratorElement.php,Configuration/GeneratorElementGuard.php}
