services:
    # [ 1 , 2];
    PhpCsFixer\Fixer\ArrayNotation\NoWhitespaceBeforeCommaInArrayFixer: ~

    # [    1, 2   ];
    PhpCsFixer\Fixer\ArrayNotation\TrimArraySpacesFixer: ~

    # [ 1,\n2 ];
    PhpCsFixer\Fixer\ArrayNotation\TrailingCommaInMultilineArrayFixer: ~

    # array(    );
    PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer:
        syntax: short

    # [1,2]
    PhpCsFixer\Fixer\ArrayNotation\WhitespaceAfterCommaInArrayFixer: ~

    PhpCsFixer\Fixer\Whitespace\ArrayIndentationFixer: ~
