services:
    _defaults:
        autowire: true

    Symplify\EasyCodingStandard\SniffRunner\:
        resource: '..'
        exclude: '../{Exception,File/File.php,Event}'

    # for tests
    Symplify\EasyCodingStandard\SniffRunner\Application\SniffFileProcessor:
        public: true

    Symplify\EasyCodingStandard\SniffRunner\Fixer\Fixer:
        public: true
