services:
    _defaults:
        autowire: true
        public: true # for tests

    Symplify\EasyCodingStandard\SniffRunner\:
        resource: '..'
        exclude: '../{Exception,File/File.php,Event}'
