services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symplify\EasyHydrator\:
        resource: '../src'
        exclude:
            - '../src/DepencencyInjection/*'
            - '../src/EasyHydratorBundle.php'

    Symfony\Component\Cache\Adapter\FilesystemAdapter: null
    Symplify\PackageBuilder\Strings\StringFormatConverter: null
