services:
    _defaults:
        autowire: true
        bind:
            $maxLineLength: '%max_line_length%'

    Symplify\TokenRunner\:
        resource: '..'
        exclude: '../{Naming/Name/Name.php,Analyzer/FixerAnalyzer/BlockStartAndEndInfo.php}'
