services:
    _defaults:
        autowire: true
        bind:
            $breakLongLines: '%break_long_lines%'
            $inlineShortLines: '%inline_short_lines%'

    Symplify\TokenRunner\:
        resource: '..'
        exclude: '../{Naming/Name/Name.php,Analyzer/FixerAnalyzer/BlockInfo.php,Wrapper/*Wrapper/*Wrapper.php}'
