services:
    _defaults:
        autowire: true

    Symplify\TokenRunner\:
        resource: '../{Analyzer,DocBlock,Guard,Transformer,Wrapper/*Wrapper/*Factory.php,Naming}'
        exclude: '../{Naming/Name/Name.php}'
