parameters:
    enable_default_release_workers: true
    is_stage_required: false

services:
    _defaults:
        public: true
        autowire: true

    Symplify\MonorepoBuilder\Release\:
        resource: '../src'
        exclude: '../src/Exception'
