language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
    depth: false

matrix:
    include:
        - php: 7.1
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
        - php: 7.3

install:
    - composer update --prefer-source $COMPOSER_FLAGS

script:
    - bin/changelog-linker
    - vendor/bin/phpunit

notifications:
    email: false
