language: php

php:
  - 7.1

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml" CHECK_CS=true

install:
  - composer install --prefer-source

script:
  # run tests
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # check coding standard
  - if [[ $CHECK_CS != "" ]]; then composer fix-cs; fi

after_script:
  # get scrutinizer and upload coverage
  - if [[ $PHPUNIT_FLAGS != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
