services:
    _defaults:
        autowire: true
        public: true

    Symplify\BetterPhpDocParser\:
        resource: '../src'
        exclude: '../src/{DependencyInjection,HttpKernel,PhpDocParser/Ast/Type/*,*/*Info.php,*Info.php,PhpDocParser/Ast/PhpDoc}'

    PHPStan\PhpDocParser\Lexer\Lexer: ~
    PHPStan\PhpDocParser\Parser\TypeParser: ~
    PHPStan\PhpDocParser\Parser\ConstExprParser: ~
    Symplify\PackageBuilder\Php\TypeAnalyzer: ~

    PHPStan\PhpDocParser\Parser\PhpDocParser:
        alias: 'Symplify\BetterPhpDocParser\PhpDocParser\PositionAwarePhpDocParser'
