services:
    SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff: ~
    SlevomatCodingStandard\Sniffs\Functions\UnusedInheritedVariablePassedToClosureSniff: ~
    SlevomatCodingStandard\Sniffs\Functions\UnusedParameterSniff: ~
    SlevomatCodingStandard\Sniffs\Variables\UnusedVariableSniff: ~
    SlevomatCodingStandard\Sniffs\Namespaces\UnusedUsesSniff: ~
