services:
    symplify.filter_manager:
        class: Symplify\ModularDoctrineFilters\Filter\FilterManager
        autowire: true

    symplify.enable_filters_listener:
        class: Symplify\ModularDoctrineFilters\EventListener\EnableFiltersSubscriber
        autwoire: true
#        tags:
#            - { name: kernel.event_listener, event: kernel.request }
