services:
    _defaults:
        public: true
        autowire: true

    Symplify\Statie\Latte\:
        resource: '../src'
        exclude: '../src/{Exception}'

    Latte\ILoader: '@Symplify\Statie\Latte\Loader\ArrayLoader'
