services:
    _defaults:
        public: true
        autowire: true

    Symplify\MonorepoBuilder\:
        resource: '../src'
        exclude: '../src/{Contract,Exception,HttpKernel/MonorepoBuilderKernel.php}'

    # alias needed for Symfony Console setter
    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        alias: 'Symfony\Component\EventDispatcher\EventDispatcher'

    Symfony\Component\Filesystem\Filesystem: ~

    Symplify\PackageBuilder\Reflection\PrivatesCaller: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~
    Symplify\PackageBuilder\Yaml\ParametersMerger: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
