name: After Split Coding Standard

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: |
                    composer install --no-progress
                    packages/monorepo-builder/bin/monorepo-builder localize-composer-paths

                    cd packages/coding-standard

                    # todo use local
                    composer update --no-progress
                    vendor/bin/phpunit
