name: Binary Files

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    # test run bin files
                    packages/Autodiscovery/bin/autodiscovery
                    packages/EasyCodingStandard/bin/ecs
                    packages/ChangelogLinker/bin/changelog-linker
                    packages/Statie/bin/statie
                    packages/LatteToTwigConverter/bin/latte-to-twig-converter
                    packages/MonorepoBuilder/bin/monorepo-builder

                    # test "check" options
                    packages/EasyCodingStandard/bin/ecs check packages/ChangelogLinker/src --no-progress-bar --no-error-table --clear-cache
