name: Binary Files

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    # test run bin files
                    packages/autodiscovery/bin/autodiscovery
                    packages/easy-coding-standard/bin/ecs
                    packages/changelog-linker/bin/changelog-linker
                    packages/statie/bin/statie
                    packages/monorepo-builder/bin/monorepo-builder

                    # test "check" options
                    packages/easy-coding-standard/bin/ecs check packages/changelog-linker/src --no-progress-bar --no-error-table --clear-cache
