name: Build ECS Prefixed

on:
    pull_request: null

    push:
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    build_ecs_prefixed:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            # --prefer-lowest makes sure there are the same package in root + package
            -   run: composer update --no-progress --ansi

            # 1. install package dependencies
            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/easy-coding-standard/composer.json --ansi

            # --prefer-lowest makes sure there are the same package in root + package - that prevents see https://github.com/symplify/symplify/pull/2442/checks?check_run_id=1348085811#step:8:5
            -
                run: composer update --working-dir packages/easy-coding-standard --ansi --no-dev

            # 2. scope it
            -   run: vendor/bin/php-scoper add-prefix packages/easy-coding-standard --output-dir packages-scoped/easy-coding-standard --config packages/easy-coding-standard/scoper.inc.php --force --ansi
            -   run: composer dump-autoload --working-dir packages-scoped/easy-coding-standard --ansi --optimize --classmap-authoritative
            -   run: packages/package-scoper/bin/package-scoper scope-composer-json packages-scoped/easy-coding-standard/composer.json --ansi

            # 3. run it
            -   run: chmod 777 ./packages-scoped/easy-coding-standard/bin/ecs

            # 4. copy github actoins to repository, so tests run there too
            -   run: cp -R build/ecs-scoped/target-repository/. packages-scoped/easy-coding-standard

            # 5. get tag - see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            # 6. split it to remote repository
            # see https://github.com/cpina/github-action-push-to-another-repository
            -
                # Uses an action in the root directory
                uses: symplify/github-action-monorepo-split@1.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages-scoped/easy-coding-standard'
                    split-repository-organization: 'symplify'
                    split-repository-name: 'easy-coding-standard-prefixed'
                    tag: ${{ steps.previous_tag.outputs.tag }}
                    user-name: "kaizen-ci"
                    user-email: "info@kaizen-ci.org"
