name: Coding Standard README Sync

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    check_coding_standard_readme_sync:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    php ci/check_coding_standard_readme_sync.php
