# goodies inspiration - https://github.com/sdras/awesome-actions
name: CI Review

on:
    pull_request: null

jobs:
    ci_review:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: "Validate Monorepo"
                        write_run: "composer propagate --ansi"
                        commit_message: "propagate monorepo dependencies"
                        check_run: "composer validate-monorepo --ansi"

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            # workaround for missing secret in fork PRs - see https://github.com/actions/checkout/issues/298
            # see https://github.com/rectorphp/rector/commit/d395e1c28b8e6a56711dcc2e10490a82965850e4
            -
                if: github.event.pull_request.head.repo.full_name == github.repository
                uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.ACCESS_TOKEN }}

            # in forks, the token is not available - so we cannot us eit
            -
                if: github.event.pull_request.head.repo.full_name != github.repository
                uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.write_run }}

            # see https://github.com/EndBug/add-and-commit
            -
                uses: EndBug/add-and-commit@v5
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: '[ci-review] ${{ matrix.actions.commit_message }}'
                    author_name: rector-bot
                    author_email: tomas@getrector.org
                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            -   run: ${{ matrix.actions.check_run }}
