name: Code_Checks

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer check-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer rector

    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    # test run bin files
                    packages/Autodiscovery/bin/autodiscovery
                    packages/EasyCodingStandard/bin/ecs
                    packages/ChangelogLinker/bin/changelog-linker
                    packages/Statie/bin/statie
                    packages/LatteToTwigConverter/bin/latte-to-twig-converter
                    packages/MonorepoBuilder/bin/monorepo-builder

                    # test "check" options
                    packages/EasyCodingStandard/bin/ecs check packages/ChangelogLinker/src --no-progress-bar --no-error-table --clear-cache

    simple_checks:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            # validate monorepo <=> packages composer dependencies
            -   run: packages/MonorepoBuilder/bin/monorepo-builder validate
