name: Code_Checks

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run: composer install --no-progress

            -
                name: Run
                run: composer check-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run: composer install --no-progress

            -
                name: Run
                run: composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run: composer install --no-progress

            -
                name: Run
                run: composer rector

    ecs_phar_compile:
            runs-on: ubuntu-latest

            steps:
                -
                    name: Checkout code
                    uses: actions/checkout@v2

                -
                    name: Setup PHP
                    uses: shivammathur/setup-php@v1
                    with:
                        php-version: 7.2
                        coverage: none

                -
                    run:  |
                        cd packages/EasyCodingStandard/compiler
                        composer install
                        bin/compile
                        php build/box.phar info ../tmp/ecs.phar
                        ../tmp/ecs.phar

                        cd ..

                        # Deploy PHAR to https://github.com/Symplify/EasyCodingStandardPrefixed
                        # reuse tmp/rector.phar from previous job
                        git clone https://${ACCESS_TOKEN}@github.com/Symplify/EasyCodingStandardPrefixed.git > /dev/null 2>&1
                        cp tmp/ecs.phar EasyCodingStandardPrefixed/ecs.phar
                        cp tmp/ecs.phar EasyCodingStandardPrefixed/ecs
                        cd EasyCodingStandardPrefixed
                        git config user.email "action@github.com"
                        git config user.name "Github Actions"
                        git add ecs ecs.phar

                        if [ "${TRAVIS_TAG}" != "" ]; then COMMIT_MSG="ECS ${TRAVIS_TAG}"; else COMMIT_MSG="Updated ECS to commit ${TRAVIS_COMMIT}"; fi

                        git commit -m "${COMMIT_MSG}"
                        git push --quiet origin master

                        if [ "${TRAVIS_TAG}" != "" ]; then git tag "${TRAVIS_TAG}" && git push --quiet origin ${TRAVIS_TAG}; fi
                    env:
                        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    binary_files:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            -
                run: |
                    # test run bin files
                    packages/Autodiscovery/bin/autodiscovery
                    packages/EasyCodingStandard/bin/ecs
                    packages/ChangelogLinker/bin/changelog-linker
                    packages/Statie/bin/statie
                    packages/LatteToTwigConverter/bin/latte-to-twig-converter
                    packages/MonorepoBuilder/bin/monorepo-builder

                    # test "check" options
                    packages/EasyCodingStandard/bin/ecs check packages/ChangelogLinker/src --no-progress-bar --no-error-table --clear-cache

    simple_checks:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run: composer install --no-progress

            -
                name: Run
                # validate monorepo <=> packages composer dependencies
                run: packages/MonorepoBuilder/bin/monorepo-builder validate
