name: Code Coverage

on:
    push:
        branches:
            - master

jobs:
    code_coverage:
        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # needed for tests
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: pcov

            -   run: composer install --no-progress --ansi

            -
                run: |
                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    # coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
