name: Code_Checks

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        name: PHP ${{ matrix.php }} tests
        steps:
            -   uses: actions/checkout@v2
            # required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver; default is 1
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/phpunit

    test_lowest_dependencies:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer update --no-progress --prefer-lowest
            -   run: vendor/bin/phpunit

    test_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: pcov

            -   run: composer install --no-progress
            -   run : |
                    vendor/bin/phpunit --coverage-clover build/logs/clover.xml
                    # coveralls.io
                    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                    php php-coveralls.phar --verbose
                env:
                    COVERALLS_REPO_TOKEN: 'rYS9SgezlMuTKOFsiak3xD34lxNe8iQtl'

    ecs:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer check-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer rector

    binary_files:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    # test run bin files
                    packages/Autodiscovery/bin/autodiscovery
                    packages/EasyCodingStandard/bin/ecs
                    packages/ChangelogLinker/bin/changelog-linker
                    packages/Statie/bin/statie
                    packages/LatteToTwigConverter/bin/latte-to-twig-converter
                    packages/MonorepoBuilder/bin/monorepo-builder

                    # test "check" options
                    packages/EasyCodingStandard/bin/ecs check packages/ChangelogLinker/src --no-progress-bar --no-error-table --clear-cache

    simple_checks:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            # validate monorepo <=> packages composer dependencies
            -   run: packages/MonorepoBuilder/bin/monorepo-builder validate
