name: Config Class Presence

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    config_class_presence:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/config-class-presence check packages
