name: Prefixed ECS Deploy

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    # see https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32163/highlight/true#M1024
    get_tag:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -
                name: Get the version
                id: get_tag
                run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    ecs_phar_compile:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -
                name: Install
                run:  |
                    # install
                    cd packages/EasyCodingStandard/compiler
                    composer install

            -
                name: Compile ecs.phar with Box and PHP Scoper
                run:  |
                    # compile
                    cd packages/EasyCodingStandard/compiler
                    bin/compile

            -
                name: Run ecs.phar
                run:  |
                    # remove local vendor, to prevent duplicated content
                    rm -rf packages/EasyCodingStandard/vendor
                    cd packages/EasyCodingStandard
                    tmp/ecs.phar

            -
                name: Run ecs.phar with PSR-12 set
                run:  |
                    cd packages/EasyCodingStandard
                    # create dummy file
                    echo "<?php echo 'hi';" >> someFile.php
                    tmp/ecs.phar check someFile.php --set dead-code

            # Deploy PHAR to https://github.com/Symplify/EasyCodingStandardPrefixed
            -
                name: Publish ecs.phar to Symplify/EasyCodingStandardPrefixed
                run: |
                    cd packages/EasyCodingStandard

                    # reuse tmp/ecs.phar from previous job
                    git clone https://${ACCESS_TOKEN}@github.com/Symplify/EasyCodingStandardPrefixed.git > /dev/null 2>&1

                    # copy phar files inside cloned repository
                    cp tmp/ecs.phar EasyCodingStandardPrefixed/ecs.phar
                    cp tmp/ecs.phar EasyCodingStandardPrefixed/ecs

                    # go to clone repository
                    cd EasyCodingStandardPrefixed
                    git config user.name "TomasVotruba"
                    git config user.email "tomas.vot@gmail.com"
                    git add ecs ecs.phar

                    # commit with new tag, if this commit is tagged, or with normal commit
                    if [ "${CURRENT_TAG}" != "" ]; then COMMIT_MESSAGE="ECS ${CURRENT_TAG}"; else COMMIT_MESSAGE="Updated ECS to commit ${GITHUB_SHA}"; fi
                    git commit -m "${COMMIT_MESSAGE}"

                    git push --quiet origin master

                    # push tag, if this commit is tagged, or with normal push
                    if [ "${CURRENT_TAG}" != "" ]; then git tag "${CURRENT_TAG}" && git push --quiet origin ${CURRENT_TAG}; fi
                env:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    CURRENT_TAG: ${{ steps.get_tag.outputs.VERSION }}
