# these tests require master, because only here are tokens avilable
name: Master_Tests

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer install --no-progress

            # run slow api test only on master, because they require token
            -   run: vendor/bin/phpunit --group api
