name: Rector CI

on:
    pull_request: null

jobs:
    rector_ci:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == github.repository
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v1
                with:
                    # PHP 7.4, to typed test case are covered
                    php-version: 7.4
                    coverage: none
                    tools: composer:v1

            -   run: composer install --no-progress --ansi

            ## First run Rector - here can't be --dry-run !!! it would stop the job with it and not commit anything in the future
            -   run: vendor/bin/rector rectify --config rector-ci.php --ansi --no-progress-bar
            -   run: packages/easy-coding-standard/bin/ecs check --match-git-diff --fix --ansi

            -
                uses: EndBug/add-and-commit@v5
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: "[ci-review] Rector Rectify"
                    author_name: rector-bot
                    author_email: tomas@getrector.org
                env:
                    # to get push access
                    token: ${{ secrets.ACCESS_TOKEN }}
