name: Split_Monorepo

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            # required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver; default is 1
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            # split monorepo to packages - only on merge to master
            # see https://www.tomasvotruba.cz/blog/2018/07/19/how-to-make-github-and-travis-split-monorepo-to-multiple-git-repositories-for-you/
            -   run: packages/MonorepoBuilder/bin/monorepo-builder split --max-processes 7
