name: Split Tests

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            # get package json list
            -
                id: set-matrix
                run: echo "::set-output name=matrix::$(packages/monorepo-builder/bin/monorepo-builder packages-json)"

        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    split_tests:
        needs: provide_packages_json

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths ${{ matrix.package_path }}/composer.json --ansi

            -   run: composer update --no-progress --ansi --working-dir ${{ matrix.package_path }}

            -
                name: Split Tests of ${{ matrix.package_path }}
                working-directory: ${{ matrix.package_path }}
                run: vendor/bin/phpunit
