name: Split Tests

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    split_tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package_name:
                    - autowire-array-parameter
                    - smart-file-system
                    - package-builder
                    - easy-coding-standard
                    - easy-coding-standard-tester
                    - composer-json-manipulator
                    - coding-standard
                    - changelog-linker
                    - monorepo-builder
                    - flex-loader
                    - autodiscovery
                    - set-config-resolver
                    - console-color-diff
                    - easy-hydrator
                    - easy-testing
                    - phpstan-extensions
                    - symfony-static-dumper
                    - skipper
                    - phpstan-rules

        name: Split Tests of ${{ matrix.package_name }}

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none
                    tools: composer:v2

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: composer install --no-progress --ansi

            -   run: packages/monorepo-builder/bin/monorepo-builder localize-composer-paths packages/${{ matrix.package_name }}/composer.json --ansi

            -
                working-directory: packages/${{ matrix.package_name }}
                run: composer update --no-progress --ansi

            -
                working-directory: packages/${{ matrix.package_name }}
                run: vendor/bin/phpunit
