name: Split Monorepo

on:
    push:
        branches:
            - master

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            # get package json list
            -   id: set-matrix
                run: echo "::set-output name=matrix::$(packages/monorepo-builder/bin/monorepo-builder packages-json --names)"

    split_monorepo:
        needs: provide_packages_json

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

        steps:
            -   uses: actions/checkout@v2

            # https://github.com/cpina/github-action-push-to-another-repository
            -
                name: Monorepo Split of ${{ matrix.package_name }}
                uses: cpina/github-action-push-to-another-repository@master
                env:
                    API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
                with:
                    source-directory: 'packages/${{ matrix.package_name }}'
                    destination-github-username: 'symplify'
                    destination-repository-name: '${{ matrix.package_name }}'
                    user-email: tomas@getrector.org
                    target-branch: master
