name: Unit Tests

on:
    pull_request: null

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    unit_tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: ['7.2', '7.3', '7.4']

        name: PHP ${{ matrix.php }} tests

        steps:
            -   uses: actions/checkout@v2
            # required for "git tag" presence for changelog-linker git tags resolver; default is 1
            # https://github.com/actions/checkout#fetch-all-tags
            -   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: composer install --no-progress --ansi

            -   run: vendor/bin/phpunit
